# -*- coding: utf-8 -*-
#Aplayin PGP Sign
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZkiFcqICTAKqtoy8yrdrAfc0UYNeKU4
"""

import datetime

# Función para convertir una fecha y hora en epoch de Unix
def fecha_a_epoch(fecha_str):
    # Convertir la cadena de fecha a un objeto datetime
    fecha = datetime.datetime.strptime(fecha_str, '%Y-%m-%d %H:%M:%S')

    # Calcular la diferencia en segundos desde el epoch de Unix
    epoch = datetime.datetime(1970, 1, 1)
    segundos_desde_epoch = (fecha - epoch).total_seconds()

    return int(segundos_desde_epoch)

# Fecha y hora en formato de cadena (YYYY-MM-DD HH:MM:SS)
fecha_str = "2024-04-27 23:59:00"

# Obtener el valor en segundos desde el epoch de Unix
epoch_unix = fecha_a_epoch(fecha_str)

# Imprimir el valor en epoch de Unix
print("Valor en epoch de Unix:", epoch_unix)
